### ISSUE TITLE
Game crash when launch

### ISSUE THREAD

**Issue by My7ter** [ultixon/OccultCraft#16]
When I try to launch game it instantly crashes. I'm using the 5.7 version

**Comment by ultixon** [comment]
can you provide logs or the shown error?

**Comment by Draketheduck18** [comment]
[hs_err_pid10348.log](https://github.com/ultixon/OccultCraft/files/11638258/hs_err_pid10348.log)
[hs_err_pid18512.log](https://github.com/ultixon/OccultCraft/files/11638259/hs_err_pid18512.log)
[hs_err_pid23364.log](https://github.com/ultixon/OccultCraft/files/11638260/hs_err_pid23364.log)

**Comment by Doctor-nova** [comment]
Had one of my players replicate this issue on a fresh install from forge. Using version 5.7, tried reinstalling java, tried updated versions of java. Restarted several times, etc.
[occultcraft_crash.txt](https://github.com/ultixon/OccultCraft/files/11658427/occultcraft_crash.txt)

**Comment by Doctor-nova** [comment]
Same issue but it crashed after getting further in booting up the mod loader was to go in to curse forge and manually setting the JDK/JRE running environment to javaw.exe rather than java.exe
Memory was allocated to 8gb on a system with 16gb. 
This is the only mod that had this issue for this player, several other modpacks including but not limited to Another Quality Mod Pack 2, Rougelike adventures and dungeons 2, and Mineshafts and monsters.
After uninstall and reinstall, same thing happens.

Found a solution: This player was using an RX 580 with outdated drivers, the atio6axx.dll call in these logs from both me and drake are for graphics drivers. I had him update his AMD drivers and it works now.
